stages:
- url: https://github.com/agama-project/agama/
  type: git
  name: git

#- url: https://src.suse.de/pool/agama-web-ui/pulls/17

# https://build.suse.de/project/show/SUSE:SLFO:Products:SLES:16.1:TEST
# https://build.suse.de/repositories/SUSE:SLFO:Products:SLES:16.1:TEST
# binary -b must have :suffix, source not. hard to find what produces what,
# scraping the resulting repo for now
# iosc ls SUSE:SLFO:Products:SLES:16.1:TEST agama-installer-SLES:SUSE_SLE_16.1 -b -v 

# https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.1:/TEST/product/iso/SLES-16.1-Online-x86_64-Build21.1.install.iso
- url: https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.1:/TEST/product/iso/
  type: mirrorcache
  name: sles-16.1-test-iso
  files:
    - SLES-16.1-Online-x86_64-*.iso


# maps from obs package to binary rpms (wildcards)
rpms:
  agama-web-ui:
  - agama-web-ui
  agama:
  - agama
  - agama-common
  - agama-autoinstall
  - agama-cli
  - agama-cli-bash-completion
  rubygem-agama-yast:
  - ruby*-rubygem-agama-yast
  # agama-yast source rpm, but same OBS package
  - agama-yast
  agama-products:
  - agama-products-opensuse
  agama-integration-tests:
  - agama-integration-tests
