stages:
- url: https://github.com/agama-project/agama/
  type: git
  name: agama

- url: https://github.com/agama-project/integration-tests/
  type: git
  name: agama-integration-tests

#- url: https://src.suse.de/pool/agama-web-ui/pulls/17

# https://build.suse.de/project/show/SUSE:SLFO:Products:SLES:16.1:TEST
# https://build.suse.de/repositories/SUSE:SLFO:Products:SLES:16.1:TEST
# binary -b must have :suffix, source not. hard to find what produces what,
# scraping the resulting repo for now
# iosc ls SUSE:SLFO:Products:SLES:16.1:TEST agama-installer-SLES:SUSE_SLE_16.1 -b -v 

# https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.1:/TEST/product/iso/SLES-16.1-Online-x86_64-Build21.1.install.iso
- url: https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.1:/TEST/product/iso/
  internal: true
  type: mirrorcache
  name: sles-16.1-test-iso
  files:
    - SLES-16.1-Online-x86_64-*.iso

- url: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Release/images/iso/
  type: mirrorcache
  name: obs-sm-A-Release-iso
  files:
    - agama-installer.x86_64-*-Build*.iso

- url: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/
  type: mirrorcache
  name: obs-sm-A-Devel-iso
  files:
    - agama-installer.x86_64-*-Build*.iso

- url: https://build.opensuse.org/project/show/systemsmanagement:Agama:Devel
  type: obsproject
  name: obs-sm-A-Devel

- url: https://build.opensuse.org/project/show/systemsmanagement:Agama:Release
  type: obsproject
  name: obs-sm-A-Release

- url: https://build.opensuse.org/project/show/openSUSE:Factory
  type: obsproject
  name: obs-factory
  submit_requests: true

- url: https://src.suse.de/pool/
  type: giteaproject
  branch: slfo-main
  name: ibs-pool

- url: https://src.suse.de/pool/
  type: giteaproject
  branch: slfo-1.2
  name: ibs-pool-slfo1.2

# maps from obs package to binary rpms (wildcards)
rpms:
  agama-web-ui:
  - agama-web-ui
  agama:
  - agama
  - agama-common
  - agama-autoinstall
  - agama-cli
  - agama-cli-bash-completion
  rubygem-agama-yast:
  - ruby*-rubygem-agama-yast
  # agama-yast source rpm, but same OBS package
  - agama-yast
  agama-products:
  - agama-products*
  agama-integration-tests:
  - agama-integration-tests

# Maps obs package to a list of RPM spec files.
# If not specified, foo maps to a singleton [foo].
specs:
  rubygem-agama-yast:
  - rubygem-agama-yast
  - agama-yast
